### PR TITLE
Handle nil occurence in delete_matched method

### PR DESCRIPTION
**Pull request by romansklenar**
https://trello.com/c/kE9d0nQp/271-nomethoderror-undefined-method-empty-for-nilnilclass

[Here](https://github.com/GlobalWebIndex/redis-activesupport/blob/master/lib/active_support/cache/fault_tolerant_redis_store.rb#L55) in `keys` there sometimes occurs `nil` (which might happen [here](https://github.com/GlobalWebIndex/ruby-maybe_client/blob/master/lib/maybe_client.rb#L21:L37)) and then `nil.empty?` raises:

> NoMethodError: undefined method empty? for nil:NilClass.

This PR handles nils correctly.

screen shot 2017-11-22 at 18 11 22

### CODE REVIEW

**Comment by romansklenar** [comment]
@zdenal @renra @petrjanda RDY for review, I can't even request a review due to missing permissions :(
Hope that somebody from you has permissions to merge this and create a new release.

**Comment by renra** [comment]
@romansklenar LGTM. I can merge it, but could you pls. also bump the version in the [gemspec](https://github.com/GlobalWebIndex/redis-activesupport/blob/master/fault_tolerant_redis-activesupport.gemspec#L7) so that I don't have to create another PR? Also please add yourself to the [authors](https://github.com/GlobalWebIndex/redis-activesupport/blob/master/fault_tolerant_redis-activesupport.gemspec#L8).

And we could update the [homepage](https://github.com/GlobalWebIndex/redis-activesupport/blob/master/fault_tolerant_redis-activesupport.gemspec#L10) too because it still points to my github.

**Comment by romansklenar** [comment]
I don't have permissions to merge it by myself :(
screen shot 2017-11-22 at 18 36 47

Will do the rest and ping you again when it's ready, thanks!

**Comment by romansklenar** [comment]
@renra RDY again.

**Comment by renra** [comment]
@romansklenar Perfecto, thank you!

**Pull request merged**
